config/routes.rb
Rails.application.routes.draw do
  resources :super_heroes

end

app/models/super_hero.rb
class SuperHero < ActiveRecord::Base
  validates :real_name, :hero_name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/super_heroes_controller.rb
class SuperHeroesController < ApplicationController
  before_action :set_super_hero, only: [:show, :edit, :update, :destroy]

  # GET /super_heroes
  # GET /super_heroes.json
  def index
    @super_heroes = SuperHero.all
  end

  # GET /super_heroes/1
  # GET /super_heroes/1.json
  def show
  end

  # GET /super_heroes/new
  def new
    @super_hero = SuperHero.new
  end

  # GET /super_heroes/1/edit
  def edit
  end

  # POST /super_heroes
  # POST /super_heroes.json
  def create
    @super_hero = SuperHero.new(super_hero_params)

    respond_to do |format|
      if @super_hero.save
        format.html { redirect_to @super_hero, notice: 'Super hero was successfully created.' }
        format.json { render :show, status: :created, location: @super_hero }
      else
        format.html { render :new }
        format.json { render json: @super_hero.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /super_heroes/1
  # PATCH/PUT /super_heroes/1.json
  def update
    respond_to do |format|
      if @super_hero.update(super_hero_params)
        format.html { redirect_to @super_hero, notice: 'Super hero was successfully updated.' }
        format.json { render :show, status: :ok, location: @super_hero }
      else
        format.html { render :edit }
        format.json { render json: @super_hero.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /super_heroes/1
  # DELETE /super_heroes/1.json
  def destroy
    @super_hero.destroy
    respond_to do |format|
      format.html { redirect_to super_heroes_url, notice: 'Super hero was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_super_hero
      @super_hero = SuperHero.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def super_hero_params
      params.require(:super_hero).permit(:real_name, :hero_name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/super_heroes_helper.rb
module SuperHeroesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SuperHeroRails</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/super_heroes/_form.html.erb
<%= form_for(@super_hero) do |f| %>
  <% if @super_hero.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@super_hero.errors.count, "error") %> prohibited this super_hero from being saved:</h2>

      <ul>
      <% @super_hero.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :real_name %><br>
    <%= f.text_field :real_name %>
  </div>
  <div class="field">
    <%= f.label :hero_name %><br>
    <%= f.text_field :hero_name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/super_heroes/edit.html.erb
<h1>Editing super_hero</h1>

<%= render 'form' %>

<%= link_to 'Show', @super_hero %> |
<%= link_to 'Back', super_heroes_path %>

app/views/super_heroes/index.html.erb
<h1>Listing super_heroes</h1>

<table>
  <thead>
    <tr>
      <th>Real name</th>
      <th>Hero name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @super_heroes.each do |super_hero| %>
      <tr>
        <td><%= super_hero.real_name %></td>
        <td><%= super_hero.hero_name %></td>
        <td><%= link_to 'Show', super_hero %></td>
        <td><%= link_to 'Edit', edit_super_hero_path(super_hero) %></td>
        <td><%= link_to 'Destroy', super_hero, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Super hero', new_super_hero_path %>

app/views/super_heroes/new.html.erb
<h1>New super_hero</h1>

<%= render 'form' %>

<%= link_to 'Back', super_heroes_path %>

app/views/super_heroes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Real name:</strong>
  <%= @super_hero.real_name %>
</p>

<p>
  <strong>Hero name:</strong>
  <%= @super_hero.hero_name %>
</p>

<%= link_to 'Edit', edit_super_hero_path(@super_hero) %> |
<%= link_to 'Back', super_heroes_path %>